# Welcome to Jekyll!
#

# Site settings
title: Product name
description: |
  Short product description
owner: My Company Ltd.
first_published: 2019 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://your-product.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
# google analytics
gtag_id: UA-XXXXXXXXXXXXX

  

# Build settings
markdown: kramdown
#sass:
#  style: compressed
exclude:
  - '*.json'
  - 'functions'
  - 'README.md'
source: ./jekyll

